from django.db import models, connection


class StockPrediction(models.Model):
    """
    Model for storing predicted next-month product demand generated by
    Multiple Linear Regression (OLS).
    Database table: demand_predictions
    """
    prediction_id = models.BigAutoField(primary_key=True)
    product_key = models.BigIntegerField(db_index=True)
    product_id = models.CharField(max_length=255, db_index=True, null=True, blank=True)
    product_name = models.CharField(max_length=255, null=True, blank=True)
    category_name = models.CharField(max_length=255, null=True, blank=True)
    prediction_month = models.CharField(max_length=50, db_index=True)
    predicted_demand = models.IntegerField(null=True, blank=True)  # Non-negative integer forecast
    status = models.CharField(max_length=50, default='SUCCESS')    # 'SUCCESS' or 'INSUFFICIENT_DATA'
    message = models.TextField(null=True, blank=True)
    generated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = 'demand_predictions'
        unique_together = ('product_key', 'prediction_month')
        ordering = ['product_key']

    def __str__(self):
        return f"Prediction #{self.prediction_id}: {self.product_name} ({self.prediction_month}) -> {self.predicted_demand}"

    @classmethod
    def ensure_table_exists(cls):
        """
        Helper method to create the demand_predictions table dynamically if it does not exist.
        """
        with connection.cursor() as cursor:
            cursor.execute("""
                CREATE TABLE IF NOT EXISTS demand_predictions (
                    prediction_id BIGSERIAL PRIMARY KEY,
                    product_key BIGINT NOT NULL,
                    product_id TEXT,
                    product_name TEXT,
                    category_name TEXT,
                    prediction_month VARCHAR(50) NOT NULL,
                    predicted_demand INT,
                    status VARCHAR(50) DEFAULT 'SUCCESS',
                    message TEXT,
                    generated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT unique_product_prediction_month UNIQUE (product_key, prediction_month)
                );
            """)
